### ISSUE TITLE
Water-logged Obelisk

### ISSUE THREAD

**Issue by TheLotusElise** [Franco227/Roguecraft-Community-Fixes#3]
From Discord,
"Is this supposed to happen?"
"This is a known glitch" -Erzin
![image](https://github.com/Franco227/Roguecraft-Community-Fixes/assets/174653416/9b69712e-5134-4c83-8cec-2b395c7b94c5)

**Comment by Franco227** [comment]
This is a vanilla bug related to placing structures near water, resolved in 1.21 so we'll have to wait
